enum HighlightColor {
  RED
  YELLOW
  GREEN
  BLUE
}

type DocumentHighlight {
  """unique highlight id"""
  id: ID!

  """highlight creation time"""
  createdAt: DateTime!

  """highlight last udpate time"""
  updatedAt: DateTime!

  """highlight deletion time"""
  deletedAt: DateTime

  """highlight author ID"""
  createdBy: AccountInfo!

  """content associated with highlight"""
  content: JSON!

  """highlight location"""
  location: JSON!
}

type DocumentHighlightChange {
   """unique highlight id"""
  id: ID!

  """who has made a change"""
  createdBy: AccountInfo!

  """whether highlight content has been changed"""
  content: JSON!

    """whether highlight location has been changed"""
  location: JSON!

  """whether highlight has been deleted"""
  deleted: Boolean
}

input UpsertDocumentHighlightInput {
  """unique highlight id"""
  id: ID

  """content associated with highlight serialized as JSON"""
  content: JSON

  """location of a highlight serialized as JSON"""
  location: JSON

  """whether highlight has been deleted"""
  deleted: Boolean
}

extend type DocumentChange {
   """changes regarding document highlights"""
  highlights: [DocumentHighlightChange!]
}

extend type Document {
  """list of highlights associated with document"""
  highlights(limit: Int, offset: Int): [DocumentHighlight!]!
}

extend type Mutation {
  """creates or updates document highlight"""
  upsertDocumentHighlight(documentId: ID!, highlight: UpsertDocumentHighlightInput!): DocumentHighlight!
}
