type DocumentReadingInfo {
  """document creation time"""
  createdAt: DateTime!

  """document last update time"""
  updatedAt: DateTime!

  """document deletion time"""
  deletedAt: DateTime

  """account that reading info is associated with"""
  account: AccountInfo!

  """last read page"""
  lastPage: Int

  """url of screenshot image"""
  screenshot: String

  """last reading location"""
  location: String
}
