enum DocumentRole {
  ADMIN
  VIEWER
  EDITOR
}

enum DocumentType {
  PDF
}

"""user provided document metadata"""
type DocumentMeta {
  """title of the document"""
  title: String

  """document author"""
  author: String

  """document description"""
  description: String

  """keywords associated with document"""
  keywords: [String!]

  """url of document cover image"""
  cover: String

  """number of document pages"""
  pageCount: Int
}

type DocumentMember {
  """member account"""
  account: AccountInfo!

  """Role of account for document"""
  role: DocumentRole!

  """document member creation time"""
  createdAt: DateTime!

  """Time when account was accepted as member of document"""
  acceptedAt: DateTime

  """account that created document member"""
  createdBy: AccountInfo!
}

type DocumentMemberChange {
  """account id that membership has been changed for"""
  accountId: ID!

  """who has made a change"""
  createdBy: AccountInfo!

  """whether ddocument role has been changed"""
  role: DocumentRole

  """whether member has been accepted"""
  accepted: Boolean

  """whether member has been deleted"""
  deleted: Boolean
}

type DocumentChange {
  """whether document meta has been updated"""
  meta: DocumentMeta

  """whether document has been deleted"""
  deleted: Boolean

  """changes regarding document members"""
  members: [DocumentMemberChange!]

    """timestamp of change"""
  timestamp: DateTime!
}

type Document {
  """unique document ID"""
  id: ID!

  """document creation time"""
  createdAt: DateTime!

  """document last update time"""
  updatedAt: DateTime!

  """document deletion time"""
  deletedAt: DateTime

  """account that created document"""
  createdBy: AccountInfo!

  """file associated with document"""
  file: FileInfo

  """type of the document"""
  type: DocumentType!

  """metadata associated with document"""
  meta: DocumentMeta!

  """list of document members"""
  members: [DocumentMember!]!
}

input OutlineNodeInput {
  pageNumber: Int @constraint(min: 0)
  location: String
  top: Int

  title: String!
  items: [OutlineNodeInput!]
}

input DocumentOutlineInput {
  items: [OutlineNodeInput!]!
}

input DocumentMetaInput {
  """title of the document"""
  title: String

  """document author"""
  author: String

  """document description"""
  description: String

  """url of document cover image"""
  cover: String

  """number of pages in document"""
  pageCount: Int @constraint(min: 0)

  """document outline"""
  outline: DocumentOutlineInput
}

input DocumentMemberInput {
  """id of account to update"""
  accountId: ID!

  """role of document member"""
  role: DocumentRole

  """whether document member is accepted"""
  accepted: Boolean
}

input UpsertDocumentInput {
  """unique document ID"""
  id: ID

  """hash of file associated with document"""
  fileHash: String #@constraint(pattern: "^[A-Fa-f0-9]{64}$")

  """type of the document"""
  type: DocumentType

  """metadata associates with document"""
  meta: DocumentMetaInput

  """list of document members"""
  members: [DocumentMemberInput!]

  """whether to delete document"""
  deleted: Boolean
}

extend type Query {
  """gets document by id"""
  document(id: ID!): Document
}

extend type Mutation {
  """creates or updates a document"""
  upsertDocument(document: UpsertDocumentInput!): Document!
}

extend type Subscription {
  documentChanges(id: ID!): DocumentChange
}
